# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_designer\chooseclass.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ChooseClass(object):
    def setupUi(self, ChooseClass):
        ChooseClass.setObjectName("ChooseClass")
        ChooseClass.resize(800, 600)
        self.status_label = QtWidgets.QLabel(ChooseClass)
        self.status_label.setGeometry(QtCore.QRect(619, 50, 140, 40))
        self.status_label.setText("")
        self.status_label.setObjectName("status_label")
        self.adv_cb = QtWidgets.QCheckBox(ChooseClass)
        self.adv_cb.setGeometry(QtCore.QRect(330, 520, 60, 16))
        self.adv_cb.setObjectName("adv_cb")
        self.info0 = QtWidgets.QLabel(ChooseClass)
        self.info0.setGeometry(QtCore.QRect(150, 380, 20, 20))
        self.info0.setObjectName("info0")
        self.pos_cb = QtWidgets.QCheckBox(ChooseClass)
        self.pos_cb.setGeometry(QtCore.QRect(110, 490, 100, 16))
        self.pos_cb.setObjectName("pos_cb")
        self.collins_cb = QtWidgets.QCheckBox(ChooseClass)
        self.collins_cb.setGeometry(QtCore.QRect(110, 280, 100, 16))
        self.collins_cb.setObjectName("collins_cb")
        self.select_rbtn = QtWidgets.QRadioButton(ChooseClass)
        self.select_rbtn.setGeometry(QtCore.QRect(60, 140, 101, 16))
        self.select_rbtn.setObjectName("select_rbtn")
        self.prep_cb = QtWidgets.QCheckBox(ChooseClass)
        self.prep_cb.setGeometry(QtCore.QRect(270, 520, 60, 16))
        self.prep_cb.setObjectName("prep_cb")
        self.frq_slider = QtWidgets.QSlider(ChooseClass)
        self.frq_slider.setGeometry(QtCore.QRect(260, 450, 300, 20))
        self.frq_slider.setOrientation(QtCore.Qt.Horizontal)
        self.frq_slider.setObjectName("frq_slider")
        self.zk_cb = QtWidgets.QCheckBox(ChooseClass)
        self.zk_cb.setGeometry(QtCore.QRect(150, 210, 60, 16))
        self.zk_cb.setObjectName("zk_cb")
        self.bnc_slider = QtWidgets.QSlider(ChooseClass)
        self.bnc_slider.setGeometry(QtCore.QRect(260, 380, 300, 20))
        self.bnc_slider.setOrientation(QtCore.Qt.Horizontal)
        self.bnc_slider.setObjectName("bnc_slider")
        self.collins2_rbtn = QtWidgets.QRadioButton(ChooseClass)
        self.collins2_rbtn.setGeometry(QtCore.QRect(190, 310, 40, 16))
        self.collins2_rbtn.setObjectName("collins2_rbtn")
        self.all_rbtn = QtWidgets.QRadioButton(ChooseClass)
        self.all_rbtn.setGeometry(QtCore.QRect(60, 60, 151, 16))
        self.all_rbtn.setObjectName("all_rbtn")
        self.frq_cb = QtWidgets.QCheckBox(ChooseClass)
        self.frq_cb.setGeometry(QtCore.QRect(110, 420, 170, 16))
        self.frq_cb.setObjectName("frq_cb")
        self.collins3_rbtn = QtWidgets.QRadioButton(ChooseClass)
        self.collins3_rbtn.setGeometry(QtCore.QRect(230, 310, 30, 16))
        self.collins3_rbtn.setObjectName("collins3_rbtn")
        self.cet6_cb = QtWidgets.QCheckBox(ChooseClass)
        self.cet6_cb.setGeometry(QtCore.QRect(330, 210, 60, 16))
        self.cet6_cb.setObjectName("cet6_cb")
        self.collins4_rbtn = QtWidgets.QRadioButton(ChooseClass)
        self.collins4_rbtn.setGeometry(QtCore.QRect(270, 310, 31, 16))
        self.collins4_rbtn.setObjectName("collins4_rbtn")
        self.verb_cb = QtWidgets.QCheckBox(ChooseClass)
        self.verb_cb.setGeometry(QtCore.QRect(150, 520, 60, 16))
        self.verb_cb.setObjectName("verb_cb")
        self.ielts_cb = QtWidgets.QCheckBox(ChooseClass)
        self.ielts_cb.setGeometry(QtCore.QRect(150, 240, 60, 16))
        self.ielts_cb.setObjectName("ielts_cb")
        self.collins1_rbtn = QtWidgets.QRadioButton(ChooseClass)
        self.collins1_rbtn.setGeometry(QtCore.QRect(150, 310, 40, 16))
        self.collins1_rbtn.setObjectName("collins1_rbtn")
        self.n_cb = QtWidgets.QCheckBox(ChooseClass)
        self.n_cb.setGeometry(QtCore.QRect(210, 520, 60, 16))
        self.n_cb.setObjectName("n_cb")
        self.wordcount_tl = QtWidgets.QLineEdit(ChooseClass)
        self.wordcount_tl.setGeometry(QtCore.QRect(290, 60, 113, 20))
        self.wordcount_tl.setObjectName("wordcount_tl")
        self.info2 = QtWidgets.QLabel(ChooseClass)
        self.info2.setGeometry(QtCore.QRect(250, 60, 30, 16))
        self.info2.setObjectName("info2")
        self.back_btn = QtWidgets.QPushButton(ChooseClass)
        self.back_btn.setGeometry(QtCore.QRect(660, 220, 100, 30))
        self.back_btn.setObjectName("back_btn")
        self.frq_tl = QtWidgets.QLineEdit(ChooseClass)
        self.frq_tl.setGeometry(QtCore.QRect(170, 450, 60, 20))
        self.frq_tl.setObjectName("frq_tl")
        self.collins5_rbtn = QtWidgets.QRadioButton(ChooseClass)
        self.collins5_rbtn.setGeometry(QtCore.QRect(310, 310, 31, 16))
        self.collins5_rbtn.setObjectName("collins5_rbtn")
        self.posothers_cb = QtWidgets.QCheckBox(ChooseClass)
        self.posothers_cb.setGeometry(QtCore.QRect(460, 520, 60, 16))
        self.posothers_cb.setObjectName("posothers_cb")
        self.toefl_cb = QtWidgets.QCheckBox(ChooseClass)
        self.toefl_cb.setGeometry(QtCore.QRect(210, 240, 60, 16))
        self.toefl_cb.setObjectName("toefl_cb")
        self.gk_cb = QtWidgets.QCheckBox(ChooseClass)
        self.gk_cb.setGeometry(QtCore.QRect(210, 210, 60, 16))
        self.gk_cb.setObjectName("gk_cb")
        self.tag_cb = QtWidgets.QCheckBox(ChooseClass)
        self.tag_cb.setGeometry(QtCore.QRect(110, 180, 121, 16))
        self.tag_cb.setObjectName("tag_cb")
        self.oxford_cb = QtWidgets.QCheckBox(ChooseClass)
        self.oxford_cb.setGeometry(QtCore.QRect(330, 240, 130, 16))
        self.oxford_cb.setObjectName("oxford_cb")
        self.cet4_cb = QtWidgets.QCheckBox(ChooseClass)
        self.cet4_cb.setGeometry(QtCore.QRect(270, 210, 60, 16))
        self.cet4_cb.setObjectName("cet4_cb")
        self.bnc_tl = QtWidgets.QLineEdit(ChooseClass)
        self.bnc_tl.setGeometry(QtCore.QRect(170, 380, 60, 20))
        self.bnc_tl.setObjectName("bnc_tl")
        self.adj_cb = QtWidgets.QCheckBox(ChooseClass)
        self.adj_cb.setGeometry(QtCore.QRect(390, 520, 70, 16))
        self.adj_cb.setObjectName("adj_cb")
        self.info1 = QtWidgets.QLabel(ChooseClass)
        self.info1.setGeometry(QtCore.QRect(150, 450, 20, 20))
        self.info1.setObjectName("info1")
        self.ky_cb = QtWidgets.QCheckBox(ChooseClass)
        self.ky_cb.setGeometry(QtCore.QRect(270, 240, 60, 16))
        self.ky_cb.setObjectName("ky_cb")
        self.bnc_cb = QtWidgets.QCheckBox(ChooseClass)
        self.bnc_cb.setGeometry(QtCore.QRect(110, 350, 200, 16))
        self.bnc_cb.setObjectName("bnc_cb")
        self.ok_btn = QtWidgets.QPushButton(ChooseClass)
        self.ok_btn.setGeometry(QtCore.QRect(660, 120, 100, 80))
        self.ok_btn.setObjectName("ok_btn")

        self.retranslateUi(ChooseClass)
        QtCore.QMetaObject.connectSlotsByName(ChooseClass)

    def retranslateUi(self, ChooseClass):
        _translate = QtCore.QCoreApplication.translate
        ChooseClass.setWindowTitle(_translate("ChooseClass", "筛选"))
        self.adv_cb.setText(_translate("ChooseClass", "副词"))
        self.info0.setText(_translate("ChooseClass", "前"))
        self.pos_cb.setText(_translate("ChooseClass", "按词性筛选"))
        self.collins_cb.setText(_translate("ChooseClass", "柯林斯星级"))
        self.select_rbtn.setText(_translate("ChooseClass", "按条件筛选"))
        self.prep_cb.setText(_translate("ChooseClass", "介词"))
        self.zk_cb.setText(_translate("ChooseClass", "中考"))
        self.collins2_rbtn.setText(_translate("ChooseClass", "2"))
        self.all_rbtn.setText(_translate("ChooseClass", "随机背诵全部单词"))
        self.frq_cb.setText(_translate("ChooseClass", "当代语料库词频顺序"))
        self.collins3_rbtn.setText(_translate("ChooseClass", "3"))
        self.cet6_cb.setText(_translate("ChooseClass", "CET6"))
        self.collins4_rbtn.setText(_translate("ChooseClass", "4"))
        self.verb_cb.setText(_translate("ChooseClass", "动词"))
        self.ielts_cb.setText(_translate("ChooseClass", "雅思"))
        self.collins1_rbtn.setText(_translate("ChooseClass", "1"))
        self.n_cb.setText(_translate("ChooseClass", "名词"))
        self.info2.setText(_translate("ChooseClass", "最多:"))
        self.back_btn.setText(_translate("ChooseClass", "返回"))
        self.collins5_rbtn.setText(_translate("ChooseClass", "5"))
        self.posothers_cb.setText(_translate("ChooseClass", "其它"))
        self.toefl_cb.setText(_translate("ChooseClass", "托福"))
        self.gk_cb.setText(_translate("ChooseClass", "高考"))
        self.tag_cb.setText(_translate("ChooseClass", "按标签筛选"))
        self.oxford_cb.setText(_translate("ChooseClass", "牛津核心3000词"))
        self.cet4_cb.setText(_translate("ChooseClass", "CET4"))
        self.adj_cb.setText(_translate("ChooseClass", "形容词"))
        self.info1.setText(_translate("ChooseClass", "前"))
        self.ky_cb.setText(_translate("ChooseClass", "考研"))
        self.bnc_cb.setText(_translate("ChooseClass", "英国国家语料库词频顺序"))
        self.ok_btn.setText(_translate("ChooseClass", "开始背诵"))

