# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_designer\chooseclass.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ChooseClass_form(object):
    def setupUi(self, ChooseClass_form):
        ChooseClass_form.setObjectName("ChooseClass_form")
        ChooseClass_form.resize(800, 600)
        self.all_rbtn = QtWidgets.QRadioButton(ChooseClass_form)
        self.all_rbtn.setGeometry(QtCore.QRect(60, 60, 141, 16))
        self.all_rbtn.setObjectName("all_rbtn")
        self.select_rbtn = QtWidgets.QRadioButton(ChooseClass_form)
        self.select_rbtn.setGeometry(QtCore.QRect(60, 140, 89, 16))
        self.select_rbtn.setObjectName("select_rbtn")
        self.ok_btn = QtWidgets.QPushButton(ChooseClass_form)
        self.ok_btn.setGeometry(QtCore.QRect(660, 120, 100, 80))
        self.ok_btn.setObjectName("ok_btn")
        self.tag_cb = QtWidgets.QCheckBox(ChooseClass_form)
        self.tag_cb.setGeometry(QtCore.QRect(110, 200, 121, 16))
        self.tag_cb.setObjectName("tag_cb")
        self.zk_cb = QtWidgets.QCheckBox(ChooseClass_form)
        self.zk_cb.setGeometry(QtCore.QRect(150, 230, 60, 16))
        self.zk_cb.setObjectName("zk_cb")
        self.gk_cb = QtWidgets.QCheckBox(ChooseClass_form)
        self.gk_cb.setGeometry(QtCore.QRect(210, 230, 60, 16))
        self.gk_cb.setObjectName("gk_cb")
        self.cet4_cb = QtWidgets.QCheckBox(ChooseClass_form)
        self.cet4_cb.setGeometry(QtCore.QRect(270, 230, 60, 16))
        self.cet4_cb.setObjectName("cet4_cb")
        self.collins3_cb = QtWidgets.QCheckBox(ChooseClass_form)
        self.collins3_cb.setGeometry(QtCore.QRect(230, 300, 71, 16))
        self.collins3_cb.setObjectName("collins3_cb")
        self.collins_cb = QtWidgets.QCheckBox(ChooseClass_form)
        self.collins_cb.setGeometry(QtCore.QRect(110, 270, 81, 16))
        self.collins_cb.setObjectName("collins_cb")
        self.cet6_cb = QtWidgets.QCheckBox(ChooseClass_form)
        self.cet6_cb.setGeometry(QtCore.QRect(330, 230, 60, 16))
        self.cet6_cb.setObjectName("cet6_cb")
        self.collins1_cb = QtWidgets.QCheckBox(ChooseClass_form)
        self.collins1_cb.setGeometry(QtCore.QRect(150, 300, 30, 16))
        self.collins1_cb.setObjectName("collins1_cb")
        self.collins2_cb = QtWidgets.QCheckBox(ChooseClass_form)
        self.collins2_cb.setGeometry(QtCore.QRect(190, 300, 71, 16))
        self.collins2_cb.setObjectName("collins2_cb")
        self.oxford_cb = QtWidgets.QCheckBox(ChooseClass_form)
        self.oxford_cb.setGeometry(QtCore.QRect(390, 230, 111, 16))
        self.oxford_cb.setObjectName("oxford_cb")
        self.back_btn = QtWidgets.QPushButton(ChooseClass_form)
        self.back_btn.setGeometry(QtCore.QRect(660, 220, 100, 23))
        self.back_btn.setObjectName("back_btn")
        self.status_label = QtWidgets.QLabel(ChooseClass_form)
        self.status_label.setGeometry(QtCore.QRect(660, 270, 100, 41))
        self.status_label.setText("")
        self.status_label.setObjectName("status_label")
        self.bnc_cb = QtWidgets.QCheckBox(ChooseClass_form)
        self.bnc_cb.setGeometry(QtCore.QRect(110, 340, 171, 16))
        self.bnc_cb.setObjectName("bnc_cb")
        self.bnc_slider = QtWidgets.QSlider(ChooseClass_form)
        self.bnc_slider.setGeometry(QtCore.QRect(260, 370, 300, 20))
        self.bnc_slider.setOrientation(QtCore.Qt.Horizontal)
        self.bnc_slider.setObjectName("bnc_slider")
        self.bnc_tl = QtWidgets.QLineEdit(ChooseClass_form)
        self.bnc_tl.setGeometry(QtCore.QRect(170, 370, 61, 20))
        self.bnc_tl.setObjectName("bnc_tl")
        self.frq_slider = QtWidgets.QSlider(ChooseClass_form)
        self.frq_slider.setGeometry(QtCore.QRect(260, 440, 300, 20))
        self.frq_slider.setOrientation(QtCore.Qt.Horizontal)
        self.frq_slider.setObjectName("frq_slider")
        self.frq_tl = QtWidgets.QLineEdit(ChooseClass_form)
        self.frq_tl.setGeometry(QtCore.QRect(170, 440, 61, 20))
        self.frq_tl.setObjectName("frq_tl")
        self.frq_cb = QtWidgets.QCheckBox(ChooseClass_form)
        self.frq_cb.setGeometry(QtCore.QRect(110, 410, 141, 16))
        self.frq_cb.setObjectName("frq_cb")
        self.wordcount_tl = QtWidgets.QLineEdit(ChooseClass_form)
        self.wordcount_tl.setGeometry(QtCore.QRect(290, 60, 113, 20))
        self.wordcount_tl.setObjectName("wordcount_tl")
        self.pos_cb = QtWidgets.QCheckBox(ChooseClass_form)
        self.pos_cb.setGeometry(QtCore.QRect(110, 480, 91, 16))
        self.pos_cb.setObjectName("pos_cb")
        self.info0 = QtWidgets.QLabel(ChooseClass_form)
        self.info0.setGeometry(QtCore.QRect(150, 370, 20, 20))
        self.info0.setObjectName("info0")
        self.info1 = QtWidgets.QLabel(ChooseClass_form)
        self.info1.setGeometry(QtCore.QRect(150, 440, 20, 20))
        self.info1.setObjectName("info1")
        self.prep_cb = QtWidgets.QCheckBox(ChooseClass_form)
        self.prep_cb.setGeometry(QtCore.QRect(270, 510, 60, 16))
        self.prep_cb.setObjectName("prep_cb")
        self.adv_cb = QtWidgets.QCheckBox(ChooseClass_form)
        self.adv_cb.setGeometry(QtCore.QRect(330, 510, 60, 16))
        self.adv_cb.setObjectName("adv_cb")
        self.verb_cb = QtWidgets.QCheckBox(ChooseClass_form)
        self.verb_cb.setGeometry(QtCore.QRect(150, 510, 60, 16))
        self.verb_cb.setObjectName("verb_cb")
        self.n_cn = QtWidgets.QCheckBox(ChooseClass_form)
        self.n_cn.setGeometry(QtCore.QRect(210, 510, 60, 16))
        self.n_cn.setObjectName("n_cn")
        self.adj_cb = QtWidgets.QCheckBox(ChooseClass_form)
        self.adj_cb.setGeometry(QtCore.QRect(390, 510, 61, 16))
        self.adj_cb.setObjectName("adj_cb")
        self.info2 = QtWidgets.QLabel(ChooseClass_form)
        self.info2.setGeometry(QtCore.QRect(250, 60, 31, 16))
        self.info2.setObjectName("info2")

        self.retranslateUi(ChooseClass_form)
        QtCore.QMetaObject.connectSlotsByName(ChooseClass_form)

    def retranslateUi(self, ChooseClass_form):
        _translate = QtCore.QCoreApplication.translate
        ChooseClass_form.setWindowTitle(_translate("ChooseClass_form", "选择种类"))
        self.all_rbtn.setText(_translate("ChooseClass_form", "随机背诵全部单词"))
        self.select_rbtn.setText(_translate("ChooseClass_form", "按条件筛选"))
        self.ok_btn.setText(_translate("ChooseClass_form", "开始背诵"))
        self.tag_cb.setText(_translate("ChooseClass_form", "按标签筛选"))
        self.zk_cb.setText(_translate("ChooseClass_form", "中考"))
        self.gk_cb.setText(_translate("ChooseClass_form", "高考"))
        self.cet4_cb.setText(_translate("ChooseClass_form", "CET4"))
        self.collins3_cb.setText(_translate("ChooseClass_form", "3"))
        self.collins_cb.setText(_translate("ChooseClass_form", "柯林斯星级"))
        self.cet6_cb.setText(_translate("ChooseClass_form", "CET6"))
        self.collins1_cb.setText(_translate("ChooseClass_form", "1"))
        self.collins2_cb.setText(_translate("ChooseClass_form", "2"))
        self.oxford_cb.setText(_translate("ChooseClass_form", "牛津核心3000词"))
        self.back_btn.setText(_translate("ChooseClass_form", "返回"))
        self.bnc_cb.setText(_translate("ChooseClass_form", "英国国家语料库词频顺序"))
        self.frq_cb.setText(_translate("ChooseClass_form", "当代语料库词频顺序"))
        self.pos_cb.setText(_translate("ChooseClass_form", "按词性筛选"))
        self.info0.setText(_translate("ChooseClass_form", "前"))
        self.info1.setText(_translate("ChooseClass_form", "前"))
        self.prep_cb.setText(_translate("ChooseClass_form", "介词"))
        self.adv_cb.setText(_translate("ChooseClass_form", "副词"))
        self.verb_cb.setText(_translate("ChooseClass_form", "动词"))
        self.n_cn.setText(_translate("ChooseClass_form", "名词"))
        self.adj_cb.setText(_translate("ChooseClass_form", "形容词"))
        self.info2.setText(_translate("ChooseClass_form", "最多:"))

