# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_designer\test.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WordBook(object):
    def setupUi(self, WordBook):
        WordBook.setObjectName("WordBook")
        WordBook.resize(800, 600)
        WordBook.setMinimumSize(QtCore.QSize(800, 600))
        WordBook.setMaximumSize(QtCore.QSize(800, 600))
        self.Main = QtWidgets.QWidget()
        self.Main.setObjectName("Main")
        self.AddWord_btn = QtWidgets.QPushButton(self.Main)
        self.AddWord_btn.setGeometry(QtCore.QRect(80, 470, 640, 60))
        self.AddWord_btn.setObjectName("AddWord_btn")
        self.RemZh_btn = QtWidgets.QPushButton(self.Main)
        self.RemZh_btn.setGeometry(QtCore.QRect(420, 240, 300, 200))
        self.RemZh_btn.setObjectName("RemZh_btn")
        self.Setting_btn = QtWidgets.QPushButton(self.Main)
        self.Setting_btn.setGeometry(QtCore.QRect(0, 0, 61, 30))
        self.Setting_btn.setObjectName("Setting_btn")
        self.WordStatus_label = QtWidgets.QLabel(self.Main)
        self.WordStatus_label.setGeometry(QtCore.QRect(80, 110, 641, 61))
        self.WordStatus_label.setObjectName("WordStatus_label")
        self.RemEn_btn = QtWidgets.QPushButton(self.Main)
        self.RemEn_btn.setGeometry(QtCore.QRect(80, 240, 300, 200))
        self.RemEn_btn.setObjectName("RemEn_btn")
        self.Version_label = QtWidgets.QLabel(self.Main)
        self.Version_label.setGeometry(QtCore.QRect(730, 580, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Version_label.setFont(font)
        self.Version_label.setObjectName("Version_label")
        self.about_btn_2 = QtWidgets.QPushButton(self.Main)
        self.about_btn_2.setGeometry(QtCore.QRect(60, 0, 61, 30))
        self.about_btn_2.setObjectName("about_btn_2")
        WordBook.addWidget(self.Main)
        self.choose_en = QtWidgets.QWidget()
        self.choose_en.setObjectName("choose_en")
        self.frq_cb_en = QtWidgets.QCheckBox(self.choose_en)
        self.frq_cb_en.setGeometry(QtCore.QRect(100, 410, 170, 16))
        self.frq_cb_en.setObjectName("frq_cb_en")
        self.prep_cb_en = QtWidgets.QCheckBox(self.choose_en)
        self.prep_cb_en.setGeometry(QtCore.QRect(260, 510, 60, 16))
        self.prep_cb_en.setObjectName("prep_cb_en")
        self.adj_cb_en = QtWidgets.QCheckBox(self.choose_en)
        self.adj_cb_en.setGeometry(QtCore.QRect(380, 510, 70, 16))
        self.adj_cb_en.setObjectName("adj_cb_en")
        self.gk_cb_en = QtWidgets.QCheckBox(self.choose_en)
        self.gk_cb_en.setGeometry(QtCore.QRect(200, 200, 60, 16))
        self.gk_cb_en.setObjectName("gk_cb_en")
        self.bnc_cb_en = QtWidgets.QCheckBox(self.choose_en)
        self.bnc_cb_en.setGeometry(QtCore.QRect(100, 340, 200, 16))
        self.bnc_cb_en.setObjectName("bnc_cb_en")
        self.oxford_cb_en = QtWidgets.QCheckBox(self.choose_en)
        self.oxford_cb_en.setGeometry(QtCore.QRect(320, 230, 130, 16))
        self.oxford_cb_en.setObjectName("oxford_cb_en")
        self.frq_tl_en = QtWidgets.QLineEdit(self.choose_en)
        self.frq_tl_en.setGeometry(QtCore.QRect(160, 440, 60, 20))
        self.frq_tl_en.setObjectName("frq_tl_en")
        self.collins3_rbtn_en = QtWidgets.QRadioButton(self.choose_en)
        self.collins3_rbtn_en.setGeometry(QtCore.QRect(220, 300, 30, 16))
        self.collins3_rbtn_en.setObjectName("collins3_rbtn_en")
        self.bnc_tl_en = QtWidgets.QLineEdit(self.choose_en)
        self.bnc_tl_en.setGeometry(QtCore.QRect(160, 370, 60, 20))
        self.bnc_tl_en.setObjectName("bnc_tl_en")
        self.cet6_cb_en = QtWidgets.QCheckBox(self.choose_en)
        self.cet6_cb_en.setGeometry(QtCore.QRect(320, 200, 60, 16))
        self.cet6_cb_en.setObjectName("cet6_cb_en")
        self.collins5_rbtn_en = QtWidgets.QRadioButton(self.choose_en)
        self.collins5_rbtn_en.setGeometry(QtCore.QRect(300, 300, 31, 16))
        self.collins5_rbtn_en.setObjectName("collins5_rbtn_en")
        self.zk_cb_en = QtWidgets.QCheckBox(self.choose_en)
        self.zk_cb_en.setGeometry(QtCore.QRect(140, 200, 60, 16))
        self.zk_cb_en.setObjectName("zk_cb_en")
        self.collins2_rbtn_en = QtWidgets.QRadioButton(self.choose_en)
        self.collins2_rbtn_en.setGeometry(QtCore.QRect(180, 300, 40, 16))
        self.collins2_rbtn_en.setObjectName("collins2_rbtn_en")
        self.wordcount_tl_en = QtWidgets.QLineEdit(self.choose_en)
        self.wordcount_tl_en.setGeometry(QtCore.QRect(280, 50, 113, 20))
        self.wordcount_tl_en.setObjectName("wordcount_tl_en")
        self.toefl_cb_en = QtWidgets.QCheckBox(self.choose_en)
        self.toefl_cb_en.setGeometry(QtCore.QRect(200, 230, 60, 16))
        self.toefl_cb_en.setObjectName("toefl_cb_en")
        self.back_btn_en = QtWidgets.QPushButton(self.choose_en)
        self.back_btn_en.setGeometry(QtCore.QRect(650, 210, 100, 30))
        self.back_btn_en.setObjectName("back_btn_en")
        self.info1_en = QtWidgets.QLabel(self.choose_en)
        self.info1_en.setGeometry(QtCore.QRect(140, 440, 20, 20))
        self.info1_en.setObjectName("info1_en")
        self.ielts_cb_en = QtWidgets.QCheckBox(self.choose_en)
        self.ielts_cb_en.setGeometry(QtCore.QRect(140, 230, 60, 16))
        self.ielts_cb_en.setObjectName("ielts_cb_en")
        self.all_rbtn_en = QtWidgets.QRadioButton(self.choose_en)
        self.all_rbtn_en.setGeometry(QtCore.QRect(50, 50, 151, 16))
        self.all_rbtn_en.setObjectName("all_rbtn_en")
        self.bnc_slider_en = QtWidgets.QSlider(self.choose_en)
        self.bnc_slider_en.setGeometry(QtCore.QRect(250, 370, 300, 20))
        self.bnc_slider_en.setOrientation(QtCore.Qt.Horizontal)
        self.bnc_slider_en.setObjectName("bnc_slider_en")
        self.status_label_en = QtWidgets.QLabel(self.choose_en)
        self.status_label_en.setGeometry(QtCore.QRect(609, 40, 140, 40))
        self.status_label_en.setText("")
        self.status_label_en.setObjectName("status_label_en")
        self.tag_cb_en = QtWidgets.QCheckBox(self.choose_en)
        self.tag_cb_en.setGeometry(QtCore.QRect(100, 170, 121, 16))
        self.tag_cb_en.setObjectName("tag_cb_en")
        self.verb_cb_en = QtWidgets.QCheckBox(self.choose_en)
        self.verb_cb_en.setGeometry(QtCore.QRect(140, 510, 60, 16))
        self.verb_cb_en.setObjectName("verb_cb_en")
        self.cet4_cb_en = QtWidgets.QCheckBox(self.choose_en)
        self.cet4_cb_en.setGeometry(QtCore.QRect(260, 200, 60, 16))
        self.cet4_cb_en.setObjectName("cet4_cb_en")
        self.info0_en = QtWidgets.QLabel(self.choose_en)
        self.info0_en.setGeometry(QtCore.QRect(140, 370, 20, 20))
        self.info0_en.setObjectName("info0_en")
        self.adv_cb_en = QtWidgets.QCheckBox(self.choose_en)
        self.adv_cb_en.setGeometry(QtCore.QRect(320, 510, 60, 16))
        self.adv_cb_en.setObjectName("adv_cb_en")
        self.info2_en = QtWidgets.QLabel(self.choose_en)
        self.info2_en.setGeometry(QtCore.QRect(240, 50, 30, 16))
        self.info2_en.setObjectName("info2_en")
        self.posothers_cb_en = QtWidgets.QCheckBox(self.choose_en)
        self.posothers_cb_en.setGeometry(QtCore.QRect(450, 510, 60, 16))
        self.posothers_cb_en.setObjectName("posothers_cb_en")
        self.ky_cb_en = QtWidgets.QCheckBox(self.choose_en)
        self.ky_cb_en.setGeometry(QtCore.QRect(260, 230, 60, 16))
        self.ky_cb_en.setObjectName("ky_cb_en")
        self.frq_slider_en = QtWidgets.QSlider(self.choose_en)
        self.frq_slider_en.setGeometry(QtCore.QRect(250, 440, 300, 20))
        self.frq_slider_en.setOrientation(QtCore.Qt.Horizontal)
        self.frq_slider_en.setObjectName("frq_slider_en")
        self.collins4_rbtn_en = QtWidgets.QRadioButton(self.choose_en)
        self.collins4_rbtn_en.setGeometry(QtCore.QRect(260, 300, 31, 16))
        self.collins4_rbtn_en.setObjectName("collins4_rbtn_en")
        self.beginrecog_btn_en = QtWidgets.QPushButton(self.choose_en)
        self.beginrecog_btn_en.setGeometry(QtCore.QRect(650, 110, 100, 80))
        self.beginrecog_btn_en.setObjectName("beginrecog_btn_en")
        self.collins_cb_en = QtWidgets.QCheckBox(self.choose_en)
        self.collins_cb_en.setGeometry(QtCore.QRect(100, 270, 100, 16))
        self.collins_cb_en.setObjectName("collins_cb_en")
        self.collins1_rbtn_en = QtWidgets.QRadioButton(self.choose_en)
        self.collins1_rbtn_en.setGeometry(QtCore.QRect(140, 300, 40, 16))
        self.collins1_rbtn_en.setObjectName("collins1_rbtn_en")
        self.pos_cb_en = QtWidgets.QCheckBox(self.choose_en)
        self.pos_cb_en.setGeometry(QtCore.QRect(100, 480, 100, 16))
        self.pos_cb_en.setObjectName("pos_cb_en")
        self.n_cb_en = QtWidgets.QCheckBox(self.choose_en)
        self.n_cb_en.setGeometry(QtCore.QRect(200, 510, 60, 16))
        self.n_cb_en.setObjectName("n_cb_en")
        self.select_rbtn_en = QtWidgets.QRadioButton(self.choose_en)
        self.select_rbtn_en.setGeometry(QtCore.QRect(50, 130, 101, 16))
        self.select_rbtn_en.setObjectName("select_rbtn_en")
        WordBook.addWidget(self.choose_en)
        self.recog_en = QtWidgets.QWidget()
        self.recog_en.setObjectName("recog_en")
        self.html_tb_en = QtWidgets.QTextBrowser(self.recog_en)
        self.html_tb_en.setGeometry(QtCore.QRect(40, 30, 670, 460))
        self.html_tb_en.setObjectName("html_tb_en")
        self.playaudio_btn_en = QtWidgets.QPushButton(self.recog_en)
        self.playaudio_btn_en.setGeometry(QtCore.QRect(720, 130, 75, 171))
        self.playaudio_btn_en.setObjectName("playaudio_btn_en")
        self.remember_btn_en = QtWidgets.QPushButton(self.recog_en)
        self.remember_btn_en.setGeometry(QtCore.QRect(40, 490, 330, 90))
        self.remember_btn_en.setObjectName("remember_btn_en")
        self.forget_btn_en = QtWidgets.QPushButton(self.recog_en)
        self.forget_btn_en.setGeometry(QtCore.QRect(380, 490, 330, 90))
        self.forget_btn_en.setObjectName("forget_btn_en")
        self.tooeasy_btn_en = QtWidgets.QPushButton(self.recog_en)
        self.tooeasy_btn_en.setGeometry(QtCore.QRect(720, 30, 75, 61))
        self.tooeasy_btn_en.setObjectName("tooeasy_btn_en")
        WordBook.addWidget(self.recog_en)
        self.detail_en = QtWidgets.QWidget()
        self.detail_en.setObjectName("detail_en")
        self.detail_tb_en = QtWidgets.QTextBrowser(self.detail_en)
        self.detail_tb_en.setGeometry(QtCore.QRect(0, 0, 800, 510))
        self.detail_tb_en.setObjectName("detail_tb_en")
        self.word_pb_en = QtWidgets.QProgressBar(self.detail_en)
        self.word_pb_en.setGeometry(QtCore.QRect(0, 510, 800, 20))
        self.word_pb_en.setProperty("value", 24)
        self.word_pb_en.setObjectName("word_pb_en")
        self.next_bt_en = QtWidgets.QPushButton(self.detail_en)
        self.next_bt_en.setGeometry(QtCore.QRect(0, 530, 800, 70))
        self.next_bt_en.setObjectName("next_bt_en")
        WordBook.addWidget(self.detail_en)
        self.choose_zh = QtWidgets.QWidget()
        self.choose_zh.setObjectName("choose_zh")
        WordBook.addWidget(self.choose_zh)
        self.recog_zh = QtWidgets.QWidget()
        self.recog_zh.setObjectName("recog_zh")
        WordBook.addWidget(self.recog_zh)
        self.detail_zh = QtWidgets.QWidget()
        self.detail_zh.setObjectName("detail_zh")
        WordBook.addWidget(self.detail_zh)
        self.addword = QtWidgets.QWidget()
        self.addword.setObjectName("addword")
        WordBook.addWidget(self.addword)
        self.setting = QtWidgets.QWidget()
        self.setting.setObjectName("setting")
        WordBook.addWidget(self.setting)
        self.success = QtWidgets.QWidget()
        self.success.setObjectName("success")
        WordBook.addWidget(self.success)
        self.about = QtWidgets.QWidget()
        self.about.setObjectName("about")
        self.label = QtWidgets.QLabel(self.about)
        self.label.setGeometry(QtCore.QRect(280, 30, 251, 41))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.about)
        self.label_2.setGeometry(QtCore.QRect(100, 110, 231, 71))
        self.label_2.setObjectName("label_2")
        WordBook.addWidget(self.about)

        self.retranslateUi(WordBook)
        WordBook.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WordBook)

    def retranslateUi(self, WordBook):
        _translate = QtCore.QCoreApplication.translate
        WordBook.setWindowTitle(_translate("WordBook", "单词本"))
        self.AddWord_btn.setText(_translate("WordBook", "添加单词"))
        self.RemZh_btn.setText(_translate("WordBook", "中文背英文"))
        self.Setting_btn.setText(_translate("WordBook", "设置"))
        self.WordStatus_label.setText(_translate("WordBook", "#单词掌握情况"))
        self.RemEn_btn.setText(_translate("WordBook", "英文背中文"))
        self.Version_label.setText(_translate("WordBook", "test version"))
        self.about_btn_2.setText(_translate("WordBook", "关于"))
        self.frq_cb_en.setText(_translate("WordBook", "当代语料库词频顺序"))
        self.prep_cb_en.setText(_translate("WordBook", "介词"))
        self.adj_cb_en.setText(_translate("WordBook", "形容词"))
        self.gk_cb_en.setText(_translate("WordBook", "高考"))
        self.bnc_cb_en.setText(_translate("WordBook", "英国国家语料库词频顺序"))
        self.oxford_cb_en.setText(_translate("WordBook", "牛津核心3000词"))
        self.collins3_rbtn_en.setText(_translate("WordBook", "3"))
        self.cet6_cb_en.setText(_translate("WordBook", "CET6"))
        self.collins5_rbtn_en.setText(_translate("WordBook", "5"))
        self.zk_cb_en.setText(_translate("WordBook", "中考"))
        self.collins2_rbtn_en.setText(_translate("WordBook", "2"))
        self.toefl_cb_en.setText(_translate("WordBook", "托福"))
        self.back_btn_en.setText(_translate("WordBook", "返回"))
        self.info1_en.setText(_translate("WordBook", "前"))
        self.ielts_cb_en.setText(_translate("WordBook", "雅思"))
        self.all_rbtn_en.setText(_translate("WordBook", "随机背诵全部单词"))
        self.tag_cb_en.setText(_translate("WordBook", "按标签筛选"))
        self.verb_cb_en.setText(_translate("WordBook", "动词"))
        self.cet4_cb_en.setText(_translate("WordBook", "CET4"))
        self.info0_en.setText(_translate("WordBook", "前"))
        self.adv_cb_en.setText(_translate("WordBook", "副词"))
        self.info2_en.setText(_translate("WordBook", "最多:"))
        self.posothers_cb_en.setText(_translate("WordBook", "其它"))
        self.ky_cb_en.setText(_translate("WordBook", "考研"))
        self.collins4_rbtn_en.setText(_translate("WordBook", "4"))
        self.beginrecog_btn_en.setText(_translate("WordBook", "开始背诵"))
        self.collins_cb_en.setText(_translate("WordBook", "柯林斯星级"))
        self.collins1_rbtn_en.setText(_translate("WordBook", "1"))
        self.pos_cb_en.setText(_translate("WordBook", "按词性筛选"))
        self.n_cb_en.setText(_translate("WordBook", "名词"))
        self.select_rbtn_en.setText(_translate("WordBook", "按条件筛选"))
        self.playaudio_btn_en.setText(_translate("WordBook", "读音"))
        self.remember_btn_en.setText(_translate("WordBook", "认识"))
        self.forget_btn_en.setText(_translate("WordBook", "不认识"))
        self.tooeasy_btn_en.setText(_translate("WordBook", "太简单"))
        self.next_bt_en.setText(_translate("WordBook", "下一个"))
        self.label.setText(_translate("WordBook", "单词本"))
        self.label_2.setText(_translate("WordBook", "TextLabel"))

