# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Option.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Option(object):
    def setupUi(self, Option):
        Option.setObjectName("Option")
        Option.resize(800, 600)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(Option)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(20, 20, 20, 20)
        self.horizontalLayout_12.setSpacing(40)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(25)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(50)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.select_all_randomly_button = QtWidgets.QRadioButton(Option)
        self.select_all_randomly_button.setObjectName("select_all_randomly_button")
        self.horizontalLayout_2.addWidget(self.select_all_randomly_button)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.info2 = QtWidgets.QLabel(Option)
        self.info2.setObjectName("info2")
        self.horizontalLayout.addWidget(self.info2)
        self.word_number_spin = QtWidgets.QSpinBox(Option)
        self.word_number_spin.setMinimumSize(QtCore.QSize(50, 0))
        self.word_number_spin.setMinimum(1)
        self.word_number_spin.setMaximum(999)
        self.word_number_spin.setObjectName("word_number_spin")
        self.horizontalLayout.addWidget(self.word_number_spin)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(20)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.select_by_condition_button = QtWidgets.QRadioButton(Option)
        self.select_by_condition_button.setObjectName("select_by_condition_button")
        self.verticalLayout_8.addWidget(self.select_by_condition_button)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(15)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tag_cb = QtWidgets.QCheckBox(Option)
        self.tag_cb.setObjectName("tag_cb")
        self.verticalLayout_2.addWidget(self.tag_cb)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.zk_cb = QtWidgets.QCheckBox(Option)
        self.zk_cb.setObjectName("zk_cb")
        self.gridLayout.addWidget(self.zk_cb, 0, 0, 1, 1)
        self.gk_cb = QtWidgets.QCheckBox(Option)
        self.gk_cb.setObjectName("gk_cb")
        self.gridLayout.addWidget(self.gk_cb, 0, 1, 1, 1)
        self.cet4_cb = QtWidgets.QCheckBox(Option)
        self.cet4_cb.setObjectName("cet4_cb")
        self.gridLayout.addWidget(self.cet4_cb, 0, 2, 1, 1)
        self.cet6_cb = QtWidgets.QCheckBox(Option)
        self.cet6_cb.setObjectName("cet6_cb")
        self.gridLayout.addWidget(self.cet6_cb, 0, 3, 1, 1)
        self.ielts_cb = QtWidgets.QCheckBox(Option)
        self.ielts_cb.setObjectName("ielts_cb")
        self.gridLayout.addWidget(self.ielts_cb, 1, 0, 1, 1)
        self.toefl_cb = QtWidgets.QCheckBox(Option)
        self.toefl_cb.setObjectName("toefl_cb")
        self.gridLayout.addWidget(self.toefl_cb, 1, 1, 1, 1)
        self.ky_cb = QtWidgets.QCheckBox(Option)
        self.ky_cb.setObjectName("ky_cb")
        self.gridLayout.addWidget(self.ky_cb, 1, 2, 1, 1)
        self.oxford_cb = QtWidgets.QCheckBox(Option)
        self.oxford_cb.setObjectName("oxford_cb")
        self.gridLayout.addWidget(self.oxford_cb, 1, 3, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.collins_cb = QtWidgets.QCheckBox(Option)
        self.collins_cb.setObjectName("collins_cb")
        self.verticalLayout_3.addWidget(self.collins_cb)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.collins4_cb = QtWidgets.QCheckBox(Option)
        self.collins4_cb.setObjectName("collins4_cb")
        self.gridLayout_2.addWidget(self.collins4_cb, 0, 3, 1, 1)
        self.collins1_cb = QtWidgets.QCheckBox(Option)
        self.collins1_cb.setObjectName("collins1_cb")
        self.gridLayout_2.addWidget(self.collins1_cb, 0, 0, 1, 1)
        self.collins2_cb = QtWidgets.QCheckBox(Option)
        self.collins2_cb.setObjectName("collins2_cb")
        self.gridLayout_2.addWidget(self.collins2_cb, 0, 1, 1, 1)
        self.collins3_cb = QtWidgets.QCheckBox(Option)
        self.collins3_cb.setObjectName("collins3_cb")
        self.gridLayout_2.addWidget(self.collins3_cb, 0, 2, 1, 1)
        self.collins5_cb = QtWidgets.QCheckBox(Option)
        self.collins5_cb.setObjectName("collins5_cb")
        self.gridLayout_2.addWidget(self.collins5_cb, 0, 4, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 8)
        self.horizontalLayout_4.setStretch(2, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.bnc_cb = QtWidgets.QCheckBox(Option)
        self.bnc_cb.setObjectName("bnc_cb")
        self.verticalLayout_4.addWidget(self.bnc_cb)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.info0 = QtWidgets.QLabel(Option)
        self.info0.setObjectName("info0")
        self.horizontalLayout_5.addWidget(self.info0)
        self.bnc_spin = QtWidgets.QSpinBox(Option)
        self.bnc_spin.setMinimum(1)
        self.bnc_spin.setMaximum(1000)
        self.bnc_spin.setObjectName("bnc_spin")
        self.horizontalLayout_5.addWidget(self.bnc_spin)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.bnc_slider = QtWidgets.QSlider(Option)
        self.bnc_slider.setMinimum(1)
        self.bnc_slider.setMaximum(1000)
        self.bnc_slider.setOrientation(QtCore.Qt.Horizontal)
        self.bnc_slider.setObjectName("bnc_slider")
        self.horizontalLayout_5.addWidget(self.bnc_slider)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(3, 10)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frq_cb = QtWidgets.QCheckBox(Option)
        self.frq_cb.setObjectName("frq_cb")
        self.verticalLayout_5.addWidget(self.frq_cb)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.info1 = QtWidgets.QLabel(Option)
        self.info1.setObjectName("info1")
        self.horizontalLayout_7.addWidget(self.info1)
        self.frq_spin = QtWidgets.QSpinBox(Option)
        self.frq_spin.setMinimum(1)
        self.frq_spin.setMaximum(1000)
        self.frq_spin.setObjectName("frq_spin")
        self.horizontalLayout_7.addWidget(self.frq_spin)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.frq_slider = QtWidgets.QSlider(Option)
        self.frq_slider.setMinimum(1)
        self.frq_slider.setMaximum(1000)
        self.frq_slider.setOrientation(QtCore.Qt.Horizontal)
        self.frq_slider.setObjectName("frq_slider")
        self.horizontalLayout_7.addWidget(self.frq_slider)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(3, 10)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pos_cb = QtWidgets.QCheckBox(Option)
        self.pos_cb.setObjectName("pos_cb")
        self.verticalLayout_6.addWidget(self.pos_cb)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verb_cb = QtWidgets.QCheckBox(Option)
        self.verb_cb.setObjectName("verb_cb")
        self.horizontalLayout_9.addWidget(self.verb_cb)
        self.n_cn = QtWidgets.QCheckBox(Option)
        self.n_cn.setObjectName("n_cn")
        self.horizontalLayout_9.addWidget(self.n_cn)
        self.prep_cb = QtWidgets.QCheckBox(Option)
        self.prep_cb.setObjectName("prep_cb")
        self.horizontalLayout_9.addWidget(self.prep_cb)
        self.adv_cb = QtWidgets.QCheckBox(Option)
        self.adv_cb.setObjectName("adv_cb")
        self.horizontalLayout_9.addWidget(self.adv_cb)
        self.adj_cb = QtWidgets.QCheckBox(Option)
        self.adj_cb.setObjectName("adj_cb")
        self.horizontalLayout_9.addWidget(self.adj_cb)
        self.other_cb = QtWidgets.QCheckBox(Option)
        self.other_cb.setObjectName("other_cb")
        self.horizontalLayout_9.addWidget(self.other_cb)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(1, 9)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.horizontalLayout_11.addLayout(self.verticalLayout_7)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 9)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.setStretch(0, 3)
        self.verticalLayout_9.setStretch(1, 7)
        self.horizontalLayout_12.addLayout(self.verticalLayout_9)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.finish_button = QtWidgets.QPushButton(Option)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.finish_button.sizePolicy().hasHeightForWidth())
        self.finish_button.setSizePolicy(sizePolicy)
        self.finish_button.setObjectName("finish_button")
        self.verticalLayout.addWidget(self.finish_button)
        self.return_button = QtWidgets.QPushButton(Option)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.return_button.sizePolicy().hasHeightForWidth())
        self.return_button.setSizePolicy(sizePolicy)
        self.return_button.setObjectName("return_button")
        self.verticalLayout.addWidget(self.return_button)
        self.horizontalLayout_12.addLayout(self.verticalLayout)
        self.horizontalLayout_12.setStretch(0, 8)
        self.horizontalLayout_12.setStretch(1, 2)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_12)

        self.retranslateUi(Option)
        self.finish_button.clicked.connect(Option.emit_settings)
        self.return_button.clicked.connect(Option.return_main)
        self.bnc_slider.valueChanged['int'].connect(self.bnc_spin.setValue)
        self.bnc_spin.valueChanged['int'].connect(self.bnc_slider.setValue)
        self.frq_slider.valueChanged['int'].connect(self.frq_spin.setValue)
        self.frq_spin.valueChanged['int'].connect(self.frq_slider.setValue)
        QtCore.QMetaObject.connectSlotsByName(Option)

    def retranslateUi(self, Option):
        _translate = QtCore.QCoreApplication.translate
        Option.setWindowTitle(_translate("Option", "筛选"))
        self.select_all_randomly_button.setText(_translate("Option", "随机背诵全部单词"))
        self.info2.setText(_translate("Option", "最多:"))
        self.select_by_condition_button.setText(_translate("Option", "按条件筛选"))
        self.tag_cb.setText(_translate("Option", "按标签筛选"))
        self.zk_cb.setText(_translate("Option", "中考"))
        self.gk_cb.setText(_translate("Option", "高考"))
        self.cet4_cb.setText(_translate("Option", "CET4"))
        self.cet6_cb.setText(_translate("Option", "CET6"))
        self.ielts_cb.setText(_translate("Option", "雅思"))
        self.toefl_cb.setText(_translate("Option", "托福"))
        self.ky_cb.setText(_translate("Option", "考研"))
        self.oxford_cb.setText(_translate("Option", "牛津核心3000词"))
        self.collins_cb.setText(_translate("Option", "柯林斯星级"))
        self.collins4_cb.setText(_translate("Option", "4"))
        self.collins1_cb.setText(_translate("Option", "1"))
        self.collins2_cb.setText(_translate("Option", "2"))
        self.collins3_cb.setText(_translate("Option", "3"))
        self.collins5_cb.setText(_translate("Option", "5"))
        self.bnc_cb.setText(_translate("Option", "英国国家语料库词频顺序"))
        self.info0.setText(_translate("Option", "前"))
        self.frq_cb.setText(_translate("Option", "当代语料库词频顺序"))
        self.info1.setText(_translate("Option", "前"))
        self.pos_cb.setText(_translate("Option", "按词性筛选"))
        self.verb_cb.setText(_translate("Option", "动词"))
        self.n_cn.setText(_translate("Option", "名词"))
        self.prep_cb.setText(_translate("Option", "介词"))
        self.adv_cb.setText(_translate("Option", "副词"))
        self.adj_cb.setText(_translate("Option", "形容词"))
        self.other_cb.setText(_translate("Option", "其它"))
        self.finish_button.setText(_translate("Option", "设定完成"))
        self.return_button.setText(_translate("Option", "返回"))

